class_name Consts

enum GameEventCategory {ITEM_TAKE}


const ABILITY_STATE_READY = "READY"
const ABILITY_STATE_BLOCKED = "STATE_BLOCKED"
const ABILITY_STATE_ACTIVATED = "ACTIVATED"
const ABILITY_STATE_DESABLED = "DESABLED"
const ABILITY_STATE_COOLDOWN = "COOLDOWN"
